language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t marcochen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true marcochen/react-test npm test -- --coverage

after_success:
  - docker build -t marcochen/fibonacci-cal-app-client ./client
  - docker build -t marcochen/fibonacci-cal-app-nginx ./nginx
  - docker build -t marcochen/fibonacci-cal-app-server ./server
  - docker build -t marcochen/fibonacci-cal-app-worker ./worker
  # login into Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push to docker hub
  - docker push marcochen/fibonacci-cal-app-client
  - docker push marcochen/fibonacci-cal-app-nginx
  - docker push marcochen/fibonacci-cal-app-server
  - docker push marcochen/fibonacci-cal-app-worker
